//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HistorialServiceApp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHistorial", ReplyAction="*")]
        HistorialServiceApp.ServiceReference1.getHistorialResponse getHistorial(HistorialServiceApp.ServiceReference1.getHistorialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHistorial", ReplyAction="*")]
        System.Threading.Tasks.Task<HistorialServiceApp.ServiceReference1.getHistorialResponse> getHistorialAsync(HistorialServiceApp.ServiceReference1.getHistorialRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHistorialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getHistorial", Namespace="http://tempuri.org/", Order=0)]
        public HistorialServiceApp.ServiceReference1.getHistorialRequestBody Body;
        
        public getHistorialRequest() {
        }
        
        public getHistorialRequest(HistorialServiceApp.ServiceReference1.getHistorialRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getHistorialRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dpi;
        
        public getHistorialRequestBody() {
        }
        
        public getHistorialRequestBody(string usuario, string dpi) {
            this.usuario = usuario;
            this.dpi = dpi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHistorialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getHistorialResponse", Namespace="http://tempuri.org/", Order=0)]
        public HistorialServiceApp.ServiceReference1.getHistorialResponseBody Body;
        
        public getHistorialResponse() {
        }
        
        public getHistorialResponse(HistorialServiceApp.ServiceReference1.getHistorialResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getHistorialResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getHistorialResult;
        
        public getHistorialResponseBody() {
        }
        
        public getHistorialResponseBody(string getHistorialResult) {
            this.getHistorialResult = getHistorialResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : HistorialServiceApp.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<HistorialServiceApp.ServiceReference1.WebService1Soap>, HistorialServiceApp.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HistorialServiceApp.ServiceReference1.getHistorialResponse HistorialServiceApp.ServiceReference1.WebService1Soap.getHistorial(HistorialServiceApp.ServiceReference1.getHistorialRequest request) {
            return base.Channel.getHistorial(request);
        }
        
        public string getHistorial(string usuario, string dpi) {
            HistorialServiceApp.ServiceReference1.getHistorialRequest inValue = new HistorialServiceApp.ServiceReference1.getHistorialRequest();
            inValue.Body = new HistorialServiceApp.ServiceReference1.getHistorialRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.dpi = dpi;
            HistorialServiceApp.ServiceReference1.getHistorialResponse retVal = ((HistorialServiceApp.ServiceReference1.WebService1Soap)(this)).getHistorial(inValue);
            return retVal.Body.getHistorialResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HistorialServiceApp.ServiceReference1.getHistorialResponse> HistorialServiceApp.ServiceReference1.WebService1Soap.getHistorialAsync(HistorialServiceApp.ServiceReference1.getHistorialRequest request) {
            return base.Channel.getHistorialAsync(request);
        }
        
        public System.Threading.Tasks.Task<HistorialServiceApp.ServiceReference1.getHistorialResponse> getHistorialAsync(string usuario, string dpi) {
            HistorialServiceApp.ServiceReference1.getHistorialRequest inValue = new HistorialServiceApp.ServiceReference1.getHistorialRequest();
            inValue.Body = new HistorialServiceApp.ServiceReference1.getHistorialRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.dpi = dpi;
            return ((HistorialServiceApp.ServiceReference1.WebService1Soap)(this)).getHistorialAsync(inValue);
        }
    }
}
